version: '3.4'

services:
  mmsdb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:BankerBox2019
      - MYSQL_DATABASE:db
    volumes:
      - //C/Projects/MultiMicroServices/db:/var/lib/mysql
    networks:
      - appnet

  mmsrabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - appnet

  mmsredis:
    image: redis
    expose:
      - 6379
    networks:
      - appnet

  multimicroservicesapp:
    image: ${DOCKER_REGISTRY-}multimicroservicesapp
    build:
      context: .
      dockerfile: MultiMicroServicesApp/Dockerfile
    environment:
      - redisurl=redis://cache
    depends_on:
      - mmsdb
      - mmsrabbitmq
      - mmsredis
    networks:
      - appnet

networks:
  appnet:
    driver: bridge