version: '3.4'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  db:
     image: mysql:5.7
     environment:
       "MYSQL_ROOT_PASSWORD": "BankerBox2019"
       "MYSQL_DATABASE": "multidb"
     volumes:
       - //C/Projects/MultiMicroServices/db:/var/lib/mysql
     restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
  mms.api:
    image: ${DOCKER_REGISTRY-}multimicroservicesapp
    ports:
      - "5001:5001"
      - "5000:5000"
    build:
      context: .
      dockerfile: MultiMicroServicesApp/Dockerfile
    depends_on:
      - db
      - rabbit
      - redis